services:
  dockerify-android:
    image: shmayro/dockerify-android:latest
    build:
      context: .
    ports:
      - "5555:5555"
    volumes:
      - ./data:/data
      - ./extras:/extras
    environment:
      - DNS=one.one.one.one
      - SDCARD_SIZE=64G
      - RAM_SIZE=8192
    privileged: true
    devices:
      - /dev/kvm
    container_name: dockerify-android
