services:
  dockerify-android:
    container_name: dockerify-android
    image: shmayro/dockerify-android:latest
    build:
      context: .
    ports:
      - "5555:5555"
    volumes:
      - ./data:/data
      - ./extras:/extras
    environment:
      - DNS=one.one.one.one
      - SDCARD_SIZE=64G
      - RAM_SIZE=8192
    privileged: true
    devices:
      - /dev/kvm
      
  scrcpy-web:
    container_name: scrcpy-web
    restart: unless-stopped
    image: shmayro/scrcpy-web:latest
    privileged: true
    ports:
      - 8000:8000
    depends_on:
      dockerify-android:
        condition: service_healthy
    command: >
      sh -c "
        adb connect dockerify-android:5555 &&
        npm start
      "